import { useEconomyActions } from './useEconomyActions'
import { useGirlfriendActions } from './useGirlfriendActions'
import { useSocialActions } from './useSocialActions'
import { useStudyActions } from './useStudyActions'
import { useLifestyleActions } from './useLifestyleActions'
import { getAvailableActions, PhaseActionEntry, ActionId } from '@/lib/phase-actions'
import type { UseGameActionsParams } from './types'

export function useGameActions({
  stats,
  setStats,
  grades,
  setGrades,
  gameTime,
  schoolType,
  scheduledExams,
  setScheduledExams,
  friends,
  setFriends,
  relationships,
  setRelationships,
  girlfriend,
  setGirlfriend,
  setGameOver,
  setGameOverReason,
  consumeAction,
  announce,
  triggerRandomEvent,
  checkForNewFriend,
  checkForNewRelationship,
  checkForNewGirlfriend,
  setShowSubjectDialog,
  currentPhase,
  dayType,
  phaseActionsRemaining,
  schoolRecord,
  setSchoolRecord,
  gainExtraAction,
  addLogEntry,
  applyCondition,
  marinatoOggi,
  handleDormi,
  onOpenStreetRace,
  onOpenJobSelection,
}: UseGameActionsParams) {
  const { handleLavoro, handleJobSelection, handleMotorino, handleShoppingMall } = useEconomyActions({
    stats,
    setStats,
    gameTime,
    consumeAction,
    announce,
    triggerRandomEvent,
    checkForNewFriend,
    checkForNewRelationship,
    checkForNewGirlfriend,
    addLogEntry,
    currentPhase,
    dayType,
    phaseActionsRemaining,
    marinatoOggi,
    onOpenStreetRace,
    onOpenJobSelection,
  })

  const {
    handleStudia,
    handleStudySubject,
    handleStudiaGruppo,
    handleCorrompi,
    handleCorrompiSubject,
    handleMinaccia,
    handleMinacciaSubject,
    handlePrepareExam,
  } = useStudyActions({
    stats,
    setStats,
    grades,
    setGrades,
    gameTime,
    scheduledExams,
    setScheduledExams,
    friends,
    setGameOver,
    setGameOverReason,
    consumeAction,
    announce,
    setShowSubjectDialog,
    currentPhase,
    dayType,
    phaseActionsRemaining,
    setSchoolRecord,
    marinatoOggi,
    addLogEntry,
  })

  const { handleGirlfriendAction, handleGirlfriendBreakup } = useGirlfriendActions({
    stats,
    setStats,
    grades,
    setGrades,
    gameTime,
    girlfriend,
    setGirlfriend,
    consumeAction,
    announce,
    addLogEntry,
    currentPhase,
    phaseActionsRemaining,
  })

  const {
    handleDisco,
    handleCinema,
    handleTryRelationship,
    handleChiacchiera,
    handleParco,
    handleTelefona,
    handleFriendAction,
  } = useSocialActions({
    stats,
    setStats,
    gameTime,
    friends,
    setFriends,
    relationships,
    setRelationships,
    setGirlfriend,
    consumeAction,
    announce,
    triggerRandomEvent,
    checkForNewFriend,
    checkForNewRelationship,
    checkForNewGirlfriend,
    currentPhase,
    dayType,
    phaseActionsRemaining,
    marinatoOggi,
    addLogEntry,
    applyCondition,
  })

  const { handlePalestra, handleLampada, handleRiposa, handleMarina } = useLifestyleActions({
    stats,
    setStats,
    gameTime,
    schoolRecord,
    setSchoolRecord,
    consumeAction,
    announce,
    triggerRandomEvent,
    checkForNewFriend,
    checkForNewRelationship,
    gainExtraAction,
    currentPhase,
    dayType,
    phaseActionsRemaining,
    marinatoOggi,
    addLogEntry,
    applyCondition,
  })

  const ACTION_HANDLER_MAP: Partial<Record<ActionId, () => void>> = {
    palestra: handlePalestra,
    lampada: handleLampada,
    lavoro: handleLavoro,    motorino: handleMotorino,
    studia: handleStudia,
    corrompi: handleCorrompi,
    minaccia: handleMinaccia,
    riposa: handleRiposa,
    dormi: handleDormi,
    disco: handleDisco,
    cinema: handleCinema,
    shopping: handleShoppingMall,
    chiacchiera: handleChiacchiera,
    parco: handleParco,
    telefona: handleTelefona,
    studia_gruppo: handleStudiaGruppo,
  }

  const availableActions: PhaseActionEntry[] = getAvailableActions(
    currentPhase,
    dayType,
    gameTime.schoolYear.currentYear,
    gameTime.schoolYear.isSchoolPeriod,
    phaseActionsRemaining <= 0
  )

  const getHandlerForAction = (id: ActionId): (() => void) | undefined =>
    ACTION_HANDLER_MAP[id]

  return {
    handlePalestra,
    handleLampada,
    handleLavoro,
    handleJobSelection,
    handleMotorino,
    handleStudia,
    handleStudySubject,
    handleStudiaGruppo,
    handleCorrompi,
    handleCorrompiSubject,
    handleMinaccia,
    handleMinacciaSubject,
    handleRiposa,
    handleDisco,
    handleCinema,
    handleShoppingMall,
    handleTryRelationship,
    handlePrepareExam,
    handleFriendAction,
    handleGirlfriendAction,
    handleGirlfriendBreakup,
    handleChiacchiera,
    handleParco,
    handleTelefona,
    handleMarina,
    availableActions,
    getHandlerForAction,
  }
}
